captcha:
  height: 80
  width: 240
  length: 6
  max_skew: 0.7
  dot_count: 80

email:
  host: smtp.qq.com
  port: 465
  from: 373900859@qq.com
  nickname: SpriteZ
  secret:
  is_ssl: true

es:
  url: http://localhost:9200
  username:
  password:
  is_console_print: true

gaode:
  enable: false
  key:

jwt:
  access_token_secret:
  refresh_token_secret:
  access_token_expiry_time: 2h
  refresh_token_expiry_time: 7d
  issuer: go_blog

mysql:
  host: 127.0.0.1
  port: 3306
  config: charset=utf8mb4&parseTime=True&loc=Local
  username: root
  password: 123456
  dbname: blog_db
  max_open_conns: 100
  max_idle_conns: 10
  log_mode: info

qiniu:
  zone: z0
  bucket:
  img_path:
  access_key: 
  secret_key: 
  use_https: true
  use_cdn_domains: true

qq:
  enable: false
  app_id: 
  app_key: 
  redirect_url: 

redis:
  host: 127.0.0.1:6379
  password: ""
  db: 0

system:
  host: 0.0.0.0
  port: 8080
  env: release
  route_prefix: api
  use_multipoint: true
  sessions_secret:
  oss_type: local

upload:
  size: 20
  path: uploads

website:
  logo: 
  full_logo:
  title: SpriteZ's Blog
  slogan: 记录生活，分享生活
  slogan_en: Record life, share life
  description: 这是一个用Go语言编写的个人博客系统，前端使用Vue3+Vite+Naive UI，后端使用Gin框架，支持多用户，多分类，标签，评论，搜索等功能。
  version: 1.0.0
  created_at: "2025-09-01"
  icp_filling: 
  public_security_filing:
  bilibili_url:
  github_url:
  gitee_url:
  name:
  job:
  address:
  email:
  qq_image:
  wechat_image:

zap:
  level: info
  file_name: log/go_blog.log
  max_size: 200
  max_backups: 5
  max_age: 30
  is_console_print: true